name: "Build Doc"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies and compile
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest versioneer
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
        cd docs && make html      
#     - uses: actions/checkout@v1
#     - uses: ammaraskar/sphinx-action@master
#       with:
#         docs-folder: "docs/"
